apiVersion: v1
kind: Service
metadata:
  name: kafka-consumer-service
spec:
  selector:
    app: kafka-consumer
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30006
  type: NodePort
